//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiRegressionTFTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiRegressionTFTests.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age,computertype,disk_capacity_as_kb,disk_model,disk_rpm,disk_type,fieldinterest,gender,gpu_manufacturer,gpu_model,gpu_processor_ddr,gpu_processor_ddr_capacity,gpu_version,mainuse,memory_capacity_as_kb,memory_mhz,memory_type,motherboard_ddrsockets,motherboard_maxram,price,processor_manufacturer,processor_mhz,processor_model,processor_numofcores
        ///29,laptop,524288000,ST500LM000-SSHD-8GB,5400,hdd,computers,male,NVIDIA,GeForce,DDR3,962560.0,940,programming,8388608,1600,DDR3,1,8388608.0,3200.0,Intel,2500.0,Core  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fake_data_out {
            get {
                return ResourceManager.GetString("fake_data_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age,int64
        ///computertype,object
        ///disk_capacity_as_kb,int64
        ///disk_model,object
        ///disk_rpm,int64
        ///disk_type,object
        ///fieldinterest,object
        ///gender,object
        ///gpu_manufacturer,object
        ///gpu_model,object
        ///gpu_processor_ddr,object
        ///gpu_processor_ddr_capacity,float64
        ///gpu_version,object
        ///mainuse,object
        ///memory_capacity_as_kb,int64
        ///memory_mhz,int64
        ///memory_type,object
        ///motherboard_ddrsockets,int64
        ///motherboard_maxram,float64
        ///price,float64
        ///processor_manufacturer,object
        ///processor_mhz,float64
        ///processor_model,object
        ///proc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fake_data_out_dtypes {
            get {
                return ResourceManager.GetString("fake_data_out_dtypes", resourceCulture);
            }
        }
    }
}
