//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HW.Bot.Resources.BotStrings", typeof(BotStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find what you have selected..
        /// </summary>
        public static string Cant_find_selected_menu_item {
            get {
                return ResourceManager.GetString("Cant_find_selected_menu_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t save your data.
        /// </summary>
        public static string cant_save_your_data {
            get {
                return ResourceManager.GetString("cant_save_your_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Bot language.
        /// </summary>
        public static string Change_Bot_language {
            get {
                return ResourceManager.GetString("Change_Bot_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your age.
        /// </summary>
        public static string Change_your_age {
            get {
                return ResourceManager.GetString("Change_your_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Gender.
        /// </summary>
        public static string Change_your_Gender {
            get {
                return ResourceManager.GetString("Change_your_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your work.
        /// </summary>
        public static string Change_your_work {
            get {
                return ResourceManager.GetString("Change_your_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age- {0}
        ///.
        /// </summary>
        public static string data_age {
            get {
                return ResourceManager.GetString("data_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender- {0}
        ///.
        /// </summary>
        public static string data_gender {
            get {
                return ResourceManager.GetString("data_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkArea- {0}.
        /// </summary>
        public static string date_workArea {
            get {
                return ResourceManager.GetString("date_workArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your age.
        /// </summary>
        public static string Enter_your_age {
            get {
                return ResourceManager.GetString("Enter_your_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Enter your age!!.
        /// </summary>
        public static string Enter_your_age_Repeat {
            get {
                return ResourceManager.GetString("Enter_your_age_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} event detected.
        /// </summary>
        public static string event_detected {
            get {
                return ResourceManager.GetString("event_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, select what you want.
        /// </summary>
        public static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get hardware recommendations for your current computer.
        /// </summary>
        public static string RecommendationMenuItemTitle {
            get {
                return ResourceManager.GetString("RecommendationMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving information of {0} from {1}.
        /// </summary>
        public static string Saving_info_of_user {
            get {
                return ResourceManager.GetString("Saving_info_of_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving your data:
        ///.
        /// </summary>
        public static string Saving_your_data {
            get {
                return ResourceManager.GetString("Saving_your_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which data you want to change.
        /// </summary>
        public static string Select_which_data_you_want_to_change {
            get {
                return ResourceManager.GetString("Select_which_data_you_want_to_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your gender.
        /// </summary>
        public static string Select_your_gender {
            get {
                return ResourceManager.GetString("Select_your_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your work or write a new one:.
        /// </summary>
        public static string Select_your_work {
            get {
                return ResourceManager.GetString("Select_your_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We see there is no information about {0} from {1}.
        ///.
        /// </summary>
        public static string There_is_No_info_about_user {
            get {
                return ResourceManager.GetString("There_is_No_info_about_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need some information of you to give you a personal results.
        /// </summary>
        public static string We_need_some_information {
            get {
                return ResourceManager.GetString("We_need_some_information", resourceCulture);
            }
        }
    }
}
